version: '3.8'

secrets:
  MYSQL_DATABASE:
    file: ./.secrets/MYSQL_DATABASE.secret
  MYSQL_PASSWORD:
    file: ./.secrets/MYSQL_PASSWORD.secret
  MYSQL_USER:
    file: ./.secrets/MYSQL_USER.secret

services:
  wiki-db:
    image: mariadb
    container_name: wiki_db_ext
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE_FILE: /run/secrets/MYSQL_DATABASE
      MARIADB_USER_FILE: /run/secrets/MYSQL_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    secrets:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - type: volume
        source: mediawiki-db
        target: /var/lib/mysql
    networks:
      - wiki

  wiki-app:
    build:
      context: .
      args:
        - buildno=${VERSION}
        - gitcommithash=${COMMIT}
        - dbname=${DBNAME}
        - dbserver=${DBSERVER}
        - dbuser=${DBUSER}
        - dbuserpwd=${DBUSERPWD}
        - server=${SERVER}
        - adminpwd=${ADMINPWD}
        - adminuser=${ADMINUSER}
      labels:
        - "at.jft.description=Mediawiki with Extensions"
        - "at.jft.department=IT"
        - "at.jft.label-with-empty-value"
    image: drhirn/mediawiki
    container_name: wiki_app_ext
    restart: unless-stopped
    depends_on:
      - wiki-db
    volumes:
      - ./images:/var/www/html/images
    ports:
      - 8080:80
    networks:
      - wiki

volumes:
  mediawiki-db:

networks:
  wiki:
    name: mediawiki
